language: cpp

compiler: gcc

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dovecot-core dovecot-dev librados-dev
    
script:
    - ./autogen.sh
    - ./configure --with-dovecot=/usr/lib/dovecot --enable-maintainer-mode --enable-debug
    - make
