sudo: required
language: cpp
services:
- docker
env:
- DOVECOT="release-2.2.21"
- DOVECOT="master-2.3"
- DOVECOT="master-2.2"
- DOVECOT="master"
before_install:
- docker volume create --name ceph_config
- docker network create --driver=bridge --subnet=192.168.100.0/24 --gateway=192.168.100.1 ceph_network
- travis_wait 30 docker run -d --net=ceph_network --name ceph_demo --mount type=tmpfs,destination=/etc/ceph -v ceph_config:/root/cfg -e MON_IP=192.168.100.2 -e CEPH_PUBLIC_NETWORK=192.168.100.0/24 -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq -e CEPH_DEMO_BUCKET=qqq ceph/daemon demo

- travis_wait 30 docker run -itd --name build --net=ceph_network -e SOURCE_VERSION=$DOVECOT -v ceph_config:/etc/ceph -v $(pwd):/repo cephdovecot/travis-build:$DOVECOT sh
- docker exec build sh -c 'printf "nameserver 8.8.8.8\n" > /etc/resolv.conf'
- docker exec build apt-get -qq update
- docker exec build apt-get -qq upgrade
before_script:
- docker exec build sh -c 'cd /usr/local/src/dovecot; git pull origin $SOURCE_VERSION'
- docker exec build sh -c 'cd /usr/local/src/dovecot; make install'
script:
- docker exec build sh -c 'cd repo; ./autogen.sh'
- docker exec build sh -c 'cd repo; ./configure --with-dovecot=/usr/local/lib/dovecot --enable-maintainer-mode --enable-debug --with-integration-tests --enable-valgrind'
- docker exec build sh -c 'cd repo; make clean install'
- docker exec build sh -c 'cd repo/src/tests; make check-valgrind'
- docker exec build sh -c 'cd repo; cat src/tests/test-suite-memcheck.log'
- docker exec build sh -c 'ldconfig'
- docker exec ceph_demo sh -c 'cp -r /etc/ceph/* /root/cfg'
- docker exec build sh -c 'chmod 777 /etc/ceph/*'
- docker exec build sh -c 'chmod -R 777 /usr/local/var/'
- docker exec --detach build sh -c 'service dovecot.service start'
- docker exec build sh -c 'cd /usr/local/bin; ./imaptest user=t%d pass=t port=10143 users=10 clients=10 error_quit secs=600 output=/var/log/imaptest.log'

- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/dovecot.log | grep \"Error:\""'
- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/dovecot.log | grep \"failed:\""'
- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/dovecot.log | grep \"Internal error\""'
- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/dovecot.log | grep \"Panic:\""'
- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/dovecot.log | grep \"Fatal:\""'
- docker exec build bash -c '/usr/local/bin/exec.sh "cat /var/log/imaptest.log | grep \"BUG:\""'

after_script:
- docker stop build ceph_demo
- docker rm build ceph_demo
- docker network rm ceph_network
- docker volume rm ceph_config

notifications:
  slack:
    secure: CZ4/u+Hl2K2/YIsjwJoghhO3zm5XkJffiXk7voppIBFSLTUHPEgSSsZCdcBgNUSh/gjMI23geQb5PgTcfuVjuexDuX5RH43pRLHKJoFPK4UHkUEucebUY1O5K0Czvw0s1Y5YWWBWoJCsYf540kIA7hi4PoyPQ+dUC0bUItYs8APLrsz2BssEnbWR9W0mo7v4N43+KSDUObxnpNGTUVhepogrw4/cmcpUeqJU0c+lt9QpV4wMkoiRgBVfX696SCegPTOq/CtOhTzHJ5R65Bv+7zImA+/AYpRtIvkJMoHY5brRNm3bYz7an0QnFJq5B+K52Q/1CU7qhH6iED/Do35HvhW7DWJ3NBnV49vD4hR8Gam0nhHsqgd8zDpA4pIYHpC2GjXKnKk5GETIz+Ju0aepccheyLzxEK1wZKM4heMVdizA4KMyYDSGyAkElWuJhCQ0SXO8NVwH5onpQtU9rWWgGAXAV4qnHoxXzsqexw6bE7sik2h/SVUdXYmhKDT4gGUlFH+RN/5xGnMOaaYYduYi4z2ueMANw6PfROT64arsRKyFaCby9MT1YgOGtDyXee2o1RfyI1FbOTEzb+q/yOrUnk0eExBzSBi8dYjJwccY2A57bYfTNYtNLDXbsQmuVjeBiZuc1RujOsnfPpklgcWAj59OwcmkjlCzrU9uC7/vzKI=
